changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-release
      - no-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: Desktop Client
      labels:
        - desktop
        - tauri
        - ui
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other Changes
      labels:
        - "*"
